Sprint 3
vadimLuzyanin/middle.messenger.praktikum.yandex pull request #4
Opened 2022-01-21 08:20 UTC by vadimLuzyanin

2022-01-21 20:51 UTC, DmitryKhitrin requested changes
Привет, работа вышла потрясающая!) Осталось только разобраться с циклическими импортами (их минусы описал в комментах) и можно переходить к четвертому спринту)

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/api/Fetch.ts
> +        headers = options.data instanceof FormData
Тут лучше сделать иначе, сделать хедер по умолчанию `{ "Content-Type": "application/json" }` и при необходимости переопределять. В сущности любой объект в теле запроса скорее всего потребует type json, не только инстанс `FormData`

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/api/Fetch.ts
> +          if (data instanceof FormData) {
Тут хватит просто проверки на наличие data, в методе GET ее можно просто не отправлять

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/api/Fetch.ts
> +          parsedResponse = responseText;
Зачем в resolve непарсящийся ответ?

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/api/types.ts
> +  last_message?: {
Тут думаю лучше будет написать тип так:

```
{
  user: User;
  item: string;
  content: string; 
}
```

Тогда изменения в типе пользователя сразу прорастут сюда

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/component.ts
> +  // hide() {
Лучше не комментировать код просто так. Если он не нужен его стоит удалить,  либо написать комментарий, зачем он здесь. Без комментов тайное предназначение обычно выветривается из головы за пару недель)

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/components/input/Input.ts
> +    if (this.props.autofocus) {
Булевые флажки принято именовать начина с is или should. `shouldFocus`

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/constants.ts
> +  login = "/",
Поля енума принято именовать с заглавной буквы

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/constants.ts
> +  login = "/",
Register, Settings

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/controllers/WSController.ts
> +// eslint-disable-next-line import/no-cycle
А вот тут eslint прав, в коде лучше избегать циклических импортов. Обычно это запах не очень правильной архитектуры и не корректного разбиения на модули

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/controllers/WSController.ts
> +// eslint-disable-next-line import/no-cycle
Нужно либо использовать `WSController` внутри authController и chatsController либо вынести их связь в отдельный контроллер. Условный ChatController, который в свою очередь и за юзером сходит и сообщения разрулит. 

Ну и вторая проблема циклических импортов - потенциальные утечки памяти, так как [GC](https://learn.javascript.ru/garbage-collection), может не разобраться, что модуль уже не используется и не вычистит его из памяти. 

циклические импорты - крит

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/controllers/authController.ts
> +      console.log(e);
Тут бы в идеале, какую-нибудь нотификацию в интерфейсе выводить, пользователи не очень умеют в чтение консоли)

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/controllers/chatsController.ts
> +      return { unread_count: 0 };
Кажется правильный вывод - вывести ошибку, а не отдавать 0 в данном случае

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/screens/main/ChatsList/ChatsList.ts
> +    // this.innerProps.searchInput = new SearchInput();
Кажется этот коммент можно удалить)

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/screens/main/ChatsList/ChatsList.ts
> +        card.component.outerProps.onClick = () => {
Чем перезаписывать onClick, можно реализовать его в виде функции принимающий колбек.
Колбек будет хранится в замыкании)

Таким образом:
- нет реассайнов;
- постоянная ссылка на функцию onClick;
-  вся сложность скрыта внтури;

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/screens/main/ChatsList/CreateChatButton/CreateChatModal/createChatModal.hbs
> +</div>
[Для гита важно, что бы файл заканчивался пустой строкой](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/screens/main/ChatsList/CreateChatButton/profileButton.hbs
> +</button>
[EOF](https://eslint.org/docs/rules/eol-last)

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/screens/main/CurrentChat/ActionButton/actionButton.hbs
> +</div>
EOF

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/screens/main/CurrentChat/ActionModal/ActionModal.ts
> +  type: "add" | "remove";
Этот union можно вынести в отдельный тип с каким-нибудь понятным названием)

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/screens/main/CurrentChat/ActionModal/actionModal.hbs
> +</div>
EOF

2022-01-21 20:51 UTC, DmitryKhitrin commented on src/screens/main/CurrentChat/MessageCard/messageCard.hbs
>  </div>
EOF

2022-01-25 09:53 UTC, vadimLuzyanin commented on src/screens/main/ChatsList/ChatsList.ts
> +        card.component.outerProps.onClick = () => {
этот проп реализован в базовом классе как и другие обработчики, слишком много изменений будет, если менять реализацию, а еще 4 спринт делать надо)

2022-01-25 09:54 UTC, vadimLuzyanin commented on src/controllers/WSController.ts
> +// eslint-disable-next-line import/no-cycle
теперь WSController просто достает все из store, токен получает через инстанс chatApi

2022-01-25 19:05 UTC, DmitryKhitrin approved these changes
Афигенно, спасибо за внесенные правки и удачи в следующем спринте, дальше только интересней!)

2022-01-27 17:30 UTC, merged